experiment:
  id: wheel_robot4
  logdir: logs
  randomseed: 42
  train_iters: 200000
  validate_every: 2500
  save_every: 5000
  print_every: 2500

dataset:
  type: robot
  basedir: cache/wheel_real_robot
  downsample_factor: 8
  no_ndc: False
  near: 0
  far: 1
  llffhold: 8

models:
  coarse:
    type: FlexibleNeRFModel
    num_layers: 4
    hidden_size: 64
    skip_connect_every: 3
    include_input_xyz: True
    log_sampling_xyz: True
    num_encoding_fn_xyz: 6
    use_viewdirs: True
    include_input_dir: True
    num_encoding_fn_dir: 4
    log_sampling_dir: True
  fine:
    type: FlexibleNeRFModel
    num_layers: 4
    hidden_size: 64
    skip_connect_every: 3
    include_input_xyz: True
    log_sampling_xyz: True
    num_encoding_fn_xyz: 6
    use_viewdirs: True
    include_input_dir: True
    num_encoding_fn_dir: 4
    log_sampling_dir: True

optimizer:
  type: Adam
  lr: 5.0E-3

scheduler:
  lr_decay: 250
  lr_decay_factor: 0.1

nerf:
  use_viewdirs: True
  encode_position_fn: positional_encoding
  encode_direction_fn: positional_encoding
  train:
    num_random_rays: 4096
    chunksize: 16384
    perturb: True
    num_coarse: 64
    num_fine: 128
    white_background: False
    radiance_field_noise_std: 1.0
    lindisp: False
  validation:
    chunksize: 16384
    perturb: False
    num_coarse: 64
    num_fine: 128
    white_background: False
    radiance_field_noise_std: 0.0
    lindisp: False